### ISSUE TITLE
Feature request: CLI and project configuration management

### ISSUE THREAD

**Issue by timbrandin** [kitematic/kitematic#880]
**Hey, shouldn't Kitematic have a command line tool (CLI) and configuration management in a Kitematicfile (docker-compose.yml)!?**

That way one could store configuration for a projects container(s) in the repository of the project just like we already do for Vagrant.

# [Kitematic CLI and configuration management](https://github.com/kitematic/kitematic/pull/881)

Store configuration for a projects container(s) in the repository and start all of it's containers from the command line.

### docker-compose.yml
```yaml
mysql:
  image: "mysql/mysql-server:5.7"
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
drupal:
  image: "timbrandin/drupal"
  ports: # (optional) Ports definitions.
    - "80"
  volumes: # (optional) Shared volumes/folders.
    - ./:/var/www
  links: # (optional) Container links.
    - "mysql:mysql"
```

## Command Line Interface – API

* `kitematic list`

  Lists the status of container(s) managed in the docker-compose.yml

* `kitematic run`

  Starts the container(s) with it's setup from the docker-compose.yml

* `kitematic stop`

  Stops the container(s) defined in the docker-compose.yml

* `kitematic remove`

  Removes the container(s) defined in the docker-compose.yml

* `kitematic restart`

  Restart the container(s) defined in the docker-compose.yml

* `kitematic init`

  Create an example docker-compose.yml

> NOTICE! If you're using the public beta version of the Kitematic tool => Then your docker-machine's name will be "dev". Change the docker machine by exporting "dev" for your DOCKERMACHINE environment variable: `export DOCKERMACHINE="dev"`. If you think it is something else you can always run: `docker-machine list`.

## Benefits

> I guess there's a ton of benefit being able to store configuration on how to get your project up and running. I've listed a few:

* Store cache in .kitematic (similar to .vagrant) on last used random ports and reuse them next time if available, which is great if you've stored passwords for .htpasswd, login-sessions, cookies or similar for your web app. 
* Get a multi-container environment up and running with links between them already setup for you.
* Choose to use NFS for shares, and have the Kitematic CLI set that up for you.
* Save/Backup configuration you've added or edited in the Kitematic GUI.
* Setup Port forwarding to Windows or OSX.
* Tools like [Puphpet](https://puphpet.com/) could autogenerate the Kitematicfile for common setups.

**Comment by FrenchBen** [comment]
@timbrandin thank you for the very detailed information and great poc (along with your code PR). 
It seems that a lot of the functionality you're putting into Kitematic already exists within other Docker products. Having 2 tools do the same thing doesn't seem like added value, unless I'm missing the bigger picture?

Have you looked at `docker-compose` regular `docker` and `docker-machine` ? Your .YAML example is verbose a docker-compose YML. 
Integrating support for a File > Open YML would make more sense, and have `docker-machine` parse it IMHO.

**Comment by timbrandin** [comment]
Ah, I see, didn't know about that. How about supporting the docker-compose.yml format and use that filename for the configuration?

I can agree on that it might not add value as there already are tools for this but at the moment compose is way harder for any beginner to install, this tool would work out of the box by installing it together with Kitematic. 

The File > Open YML would be nice, but I'd rather see something be in git than in an imported configuration file. Wouldn't you?

**Comment by FrenchBen** [comment]
:+1: on supporting the docker-compose.yml - That would be huge! 
Sorry you had to spend all of this time implementing CLI commands :[ 

How do you envision the git for YML? I would see it as a user created a file in a specific folder:
```YAML
web:
  image: nginx
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - ~/configs:/etc/configs/:ro
  environment:
    - DEBUG=true
db:
  image: postgres
```
Then had kitematic open it to manage the containers and link them accordingly.

**Comment by timbrandin** [comment]
Yes, precisely my though!

Or if you'd want a folder within that folder with your YML file.

```yaml
web:
  image: nginx
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - ./configs:/etc/configs/:ro
  environment:
    - DEBUG=true
db:
  image: postgres
```
